# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    robot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    robot_hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

robot_arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
    command_interfaces:
      []
    state_interfaces:
      []
    allow_nonzero_velocity_at_trajectory_end: true
robot_hand_controller:
  ros__parameters:
    joint: left_finger_joint